# Generated by Django 4.2.9 on 2024-05-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_detail_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="planentry",
            name="order",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.order",
            ),
        ),
    ]
