# Generated by Django 4.2.9 on 2024-01-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.order"
            ),
        ),
    ]
