# Generated by Django 4.2.9 on 2024-02-03 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_table_alter_order_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shift",
        ),
    ]
