# Generated by Django 4.2.9 on 2024-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_delete_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
