# Generated by Django 4.2.9 on 2024-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="report",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
