# Generated by Django 4.2.9 on 2024-02-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="detail",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="quantity",
        ),
        migrations.CreateModel(
            name="PlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.detail",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.plan"
                    ),
                ),
            ],
        ),
    ]
