# Generated by Django 4.2.9 on 2024-02-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(default=0, max_length=200),
        ),
    ]
